### ISSUE TITLE
Difference between information provided by /collections and /collections/collectionId

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-coverages#109]
Currently there is an expectation that `/collections/collectionId` will return a more detailed response compared to `/collections`. However, it is unclear what exactly should be returned in `/collections`.

**Comment by Schpidi** [comment]
20210303 Coverages SWG call: @cmheazel agreed to work on this as part of the ongoing effort to harmonize Common part 2 and Coverages

**Comment by jerstlouis** [comment]
SWG 2022-01-12:

Suggesting that we make progress on this regardless of the status of Common.

Common - Part 2 defines what should be present at /collections and /collections/{collectionId}, which includes the extent at both level.

In Coverages, we also require the use of the Uniform Additional Extent (for dimensions other than spatial and temporal) -- This should also be avialble at both level.

The links to the Coverage, RangeType and DomainSet could also be required at both level.
However if the link is a JSONPointer to an embedded definition of the RangeType and/or DomainSet, those should not be at the /collections level but only at /collections/{collectionId}

**Comment by chris-little** [comment]
@jerstlouis @cmheazel I strongly prefer that Coverages API requirements are not pushed up to Common Part 2, unless there is a widespread requirement from the other APIs. Keep It (Common Part 2) Simple.

**Comment by jerstlouis** [comment]
@chris-little I fully agree with that, I was not suggesting otherwise.
However, more commonality between specifications of the OGC API family = a lot more simplicity and interoperability for developers and users.

The requirement for links to the Coverage, RangeType and DomainSet at both levels and the requirement for Extent-Uniform Additional Dimensions are _Coverages_ requirements.

This specific issue is about what extra information should be returned when requesting a single collection at `/collections/{collectoinId}` vs. when requesting the list of all collections `/collections`, here specifically for _Coverages_, but guidance from _Common_ in this regard would be useful.

e.g. in EDR, are the parameter names, full temporal extent details, and query types described at both `/collections` and `/collections/{collectionId}`, or are these only included at `/collections/{collectionId}` ?

Adopting the Extent-Uniform Additional Dimensions in other specifications where it makes sense would also be a good thing -- I think it would work with EDR except for the [issue](https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/332) with the basic Common-Part 2 extents.

**Comment by cmheazel** [comment]
In API-Coverages the /collections operation is described in section 7.1 and the /collections/{collectionId} operation is described in section 7.2. Both sections refer to section 7.3 for a description of the collection resource. Section 7.3 documents the Coverage specific **extensions** to the collection resource from API-Common.  Currently the Uniform Additional Dimensions extent is the only extension identified. 
Note that the definition of the collection resource is the same for both the /collections and /collections/{collectionid} operations. The standard leaves it up to the implementer to select the best set of metadata to include with each operation. The API-Coverages standard should provide a rich set of options, but minimize required content.

**Comment by jerstlouis** [comment]
@cmheazel 

- What Coverages adds to `/collections/{collectionId}` (in addition to the UAD extent -- which is actually more of a _restriction_, than an extension) is the requirement to include 3 links to:
   - The `/coverage` resource
   - A domainset resource (either to a JSON pointer in the same document, or to the _recommended_ path `/coverage/domainset`)
   - A rangetype resource (either to a JSON pointer in the same document, or to the _recommended_ path `/coverage/rangetype`)

- This issue is mostly about those 3 links are also required as part of the object included in the array in `/collections` or not. 
   - The advantage of saying _yes_ is that it avoids an additional server roundtrip to fetch the `/collections/{collectionId}` to retrieve those links.
   - The advantage of saying _no_ is to lighten the content of `/collections`, which may already contain several collections. The domainset in particular could be is huge, e.g., the way CIS is structured, a billion points point clouds would require the billion coordinates listed in the domainset -- which is quite different than a GeneralGridCoverage where only its bounds are specified.
   - The compromise might be what I had suggested: require a liink, but recommend to link to a JSON pointer to `/collections/{collectionId}`, not to somewhere in the full `/collections`.

**Comment by cmheazel** [comment]
A new requirement has been introduced making these three links mandatory.

**Comment by chris-little** [comment]
@cmheazel @jerstlouis As I said before, as long as this is a requirement on Coverages and not on Common.

**Comment by jerstlouis** [comment]
SWG 2022-06-08

@chris-little The requirement is specific to Coverages.
The requirements have been clarified that any collection resource when conforming to GeoData coverage is required to contain links to all 3 resrouces: the coverage, domainset and rangetype.
Applied in 604f28b1756d75f7999aa95389ebb006b00bd719
