### ISSUE TITLE
disallow null as extent boundary value

### ISSUE THREAD

**Issue by pebau** [opengeospatial/ogcapi-coverages#136]
In the OAPI-Common extent definition null values are allowed (although only by way of an informal comment in the description). For a coverage this means that the domain extent in a direction containing an "unbounded" is undefined. This will break coverage applications.

It has been discussed that this describes the _potential_ extent, but then this acts more like a "coverage type definition", which is different from the concrete instance's extent. The extent property as it stands in any case defines the _concrete_ extent.

Therefore, OAPI-Coverages should contain a restricting requirement that in a coverage view (or context, whatever it will be called) a null extent value is not admitted.

PS: On a side note, if "null" wants to express "unbounded" then this is a hack, the corresponding value should be "unbounded".

**Comment by jerstlouis** [comment]
Concerns discussed in the call today (2021-07-28):
- An OGC API collection may be available using multiple mechanisms, including e.g. _Features_ and _Coverages_. It would then be problematic for _Coverages_ restrictions which would be extended to _Features_ as well.
- `null` time interval are inherited from [_Features_](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_response_4) which says:
> _The temporal extent may use null values to indicate an open time interval._
- In an _OGC API - Coverages_ implementation, a domainset resource as defined by CIS is always separately available. I have also encountered `null` values there in implementations. According to the [CIS JSON schema](https://github.com/opengeospatial/coverage-implementation-schema/blob/main/standard/schemas/1.1/json/coverage-schema.json#L53), it seems that `null` is currently allowed. When encountered, it was also used with the meaning of an open time interval.

The hope is that this extent/envelope definition, including description of dimensions beyond the 2-3 spatial and 1 temporal, be a conformance class defined in _OGC API - Common - Part 2: Geospatial data_ (see https://github.com/opengeospatial/ogcapi-common/issues/91, https://github.com/opengeospatial/ogcapi-common/issues/167, https://github.com/opengeospatial/ogcapi-common/issues/274). Perhaps a recommendation to avoid `null` values would satisfy the concerns? We could perhaps also avoid `null` values for the additional dimensions, since _Features_ seems to only allow null values specifically for the `temporal` dimension already.

**Comment by pebau** [comment]
is there anywhere an exact specification of what such a null value means for the concrete object? How does it behave on subsetting? on bbox search? etc.

**Comment by jerstlouis** [comment]
@pebau 

For _Features_ / _Common_, there is only [this](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_response_4) where it just says that it means "an open interval". However as I highlighted in https://github.com/opengeospatial/ogcapi-common/issues/196, what is meant is probably an _infinite_ interval, since an _open_ interval has a different meaning in mathematic. The example in _Features_ is the end time being set to null, presumably because the features are live data which are constantly updated and thefore constantly retrieving the collection description to update the upper bound would be impractical.

In CIS, I just found out section 17.4 pertaining to the coverage-partitioning class where it says in _17.4    Domain set constraints_:

> The sub-coverage domain sets, as well as single direct positions, must be non-overlapping (considering all axes plus the range components) and properly contained in the super-cover­age; missing boundary values are represented as a null value.
Such null values can be used whenever the actual extent of the super-coverage is not known in the super-coverage itself, **such as in timeseries where further timeslices can be appended at any time**. The representation of such a null value is defined in the concrete encodings.

That CIS meaning actually seems fully consistent with the use of `null` in the extent / envelope.

**Comment by jerstlouis** [comment]
SWG 2022-02-16: Closing this issue because the definition of the Collection extent is defined by OGC API - Common - Part 2: Geospatial data. There is also already an example where `null` is used with the same meaning in CIS for coverage-partitioning, and the interpretation is clear, therefore this should not cause any issues for _OGC API - Coverages_. It also does not affect in any way the CIS specification/encoding.
