### ISSUE TITLE
Change `range-subset=` to `properties=`

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#157]
The selection of range values to return in the output of a coverage request is very similar to the selection of [_properties_](https://github.com/opengeospatial/ogcapi-features/tree/master/proposals/property-selection) in _Features_ and of _parameter names_ in _EDR_. I suggest that we standardize on the use of `properties=` throughout the OGC API, also with the advantage that this will feel much more familiar to non-expert developers, for whom _range_ may easily have a domain connotation (e.g. the range of coordinates for which you request values), confusing this with the domain set subsetting operation (`subset=`).

(related to #155)

@Schpidi

**Comment by joanma747** [comment]
I agree that "range" is one of the most unnatural names we could have selected but, with time, I got used to it.
In SensorThings is called "observedProperties". In the Python XArray are called "data variables". In addition, there are now discussions about Essential Variables (Such as the ones for Climate: Essential Climate Variables). Properties and Variables seem natural names to me. I agree that ranges names in coverages and property names in features are equivalent concepts and I'm in favor of any effort to bring coverage and feature world closer.

(this is assuming that we forget about the GFM where features has attributes and some attributes are "geo" and some are not. I do not think we can play this game in coverages. Actually geojson has completely forgotten about this for good).

**Comment by chris-little** [comment]
In API- EDR, we used `parameter-name` as it was what our users were used to, for a long time too. 

We considered much geospatial terminology off-putting for the non-specialists. 

We also considered the O&M terminology, `observedProperty`, but thought it misleading in non-observational cases. 

`property` seemed too generic to be helpful. 

The other short-listed candidate was `variable` - something that varies with postion/time. We didn't use it because sometimes the quantity does not vary much with time (e.g. orography). I admit that is a feeble argument.

We did start using `parameter` but that was definitely confusing because OpenAPI/Swagger got it first, so moved to `parameter-name`!    

HTH

**Comment by jerstlouis** [comment]
We discussed in the SWG today and thought that perhaps `fields=` would be another option, aligning with what the RangeType response contains.

**Comment by jerstlouis** [comment]
SWG 2022-02-09: Members present suggest to go forward with `properties`.
We will accept the decision in two weeks from now if we do not get any objection or otherwise proceed with a vote.

**Comment by jerstlouis** [comment]
SWG 2022-02-23: The two weeks have passed and no new objection has been raised, therefore moving this issue to accepted changes to be applied.
