### ISSUE TITLE
Subsetting DomainSet

### ISSUE THREAD

**Issue by Schpidi** [opengeospatial/ogcapi-coverages#47]
In cases where the domainSet is huge, retrieving only subsets of it in order to formulate meaningful requests against the rangeSet is desired.

This has been explored in Testbed 14 with CloudSat data as ReferenceableGridCoverages.

**Comment by chris-little** [comment]
This is where the proposed EDR API could help, with specific use cases. I suspect the overlap would be with EDR for Polygon and Tile. And maybe Timeseries, Profile and a Point.

**Comment by jerstlouis** [comment]
In the context of discussing the Coverages implications of ( https://github.com/opengeospatial/oapi_common/issues/91 ) where in addition to a multi-bounding boxes description of an extent or interval we are proposing to add an overall envelope, new use cases for domainset subsetting of sparse n-D coverages came up.

It was proposed that subsetting the domain set on given dimension(s) might allow to return the domain where data is available in the other axes.

e.g. subsetting the domainset for a given time period might return exactly where there is data available, or subsetting the domainset for a given area might return the exact time period where data is available.

However concerns were raised about an otherwise regular axis becoming irregular.

It was pointed out that this may address some challenges in a purely Coverages API way which previously required the use of catalogs, and that it would be worthwhile to investigate the possibilities of this approach.

More discussions to follow.

**Comment by Schpidi** [comment]
Coverages SWG call: As this should be straightforward to write down it was agreed to add it as a separate conformance class to core.

**Comment by jerstlouis** [comment]
Addressed by #122
